### ISSUE TITLE
Criar o doodle para marcarmos a Reunião Geral das PyLadies

### ISSUE THREAD

**Issue by amandachagas** [PyLadiesSalvador/organization-ssa#8]
Acredito que essa deveria ser a atividade de maior urgência aqui.

Precisamos logo expor nossos horários para assim marcamos para ontem a nossa reunião geral.

@marianabarreiros você já resolveu? Coloca o link nos comentários!

**Comment by amandachagas** [comment]
Meninas, já criei. Segue o link:

https://doodle.com/poll/k4ws43gw4afmvxhd

**Comment by marianabarreiros** [comment]
Já respondi tbm
